### ISSUE TITLE
write a catch for uv sites with too much data

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/2wp-temp-observations#14]
Some uv sites have so much data that the call to NWIS takes so long, but does not fail. For example, in the latest run, partition 240 ran overnight (tried two times) and still was not successful. Wonder if there's a way to time a call out after XX minutes or something? The problem is that the call to `whatNWISdata` does not give an accurate representation of what data are available for a given site. 

Here is partition 240, and site `405356112205601` has high frequency data at multiple depths. Most sites that cause problems are high frequency lake sites with multiple depths. This site is Great Salt Lake. I dropped that site number from the partition and completed the partition 240 download outside of `loop_tasks`, but a better solution should be implemented. The easiest solution would be to filter this site. 

![image](https://user-images.githubusercontent.com/15788176/71982920-443ac800-31eb-11ea-8152-d4526d90c54d.png)

**Comment by jread-usgs** [comment]
Seems more accurate info is needed in the inventory stage in order to isolate these types of sites as their own partition? 

The NWISweb team is in town today, perhaps worth checking in briefly just to see if there is any way to inventory number of observations.

**Comment by limnoliver** [comment]
Yeah, unfortunately this one will never download, even if it is on its own. But yes, I think the solution is the same, which is being able to identify sites with over XX records.
