### ISSUE TITLE
Possible Fahrenheit values in EcoSHEDS data

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/2wp-temp-observations#17]
Some outliers in the Eco-SHEDS data appear to be in Fahrenheit, not Celsius, as the metadata suggests. Should we convert to Celsius or just drop these values, because we'll never be sure?

```
# read in data and look at egregious values (>45 deg C)
dat <- readRDS('4_other_sources/out/ecosheds_data.rds')
high <- filter(dat, mean >= 45)
high_sites <- filter(dat, location_id %in% unique(high$location_id))

# note each series (which is series_id and color in the plot) is considered 
# a single continuous time series of observed temperatures (i.e. a deployment)
ggplot(high_sites, aes(x = date, y = mean)) +
  geom_point(size = 0.5, alpha = 0.5, aes(color = factor(series_id))) +
  facet_wrap(~location_id, scales = 'free_x')
```

![image](https://user-images.githubusercontent.com/15788176/86173993-7831de80-bae6-11ea-8cc3-0d842c184c82.png)

**Comment by aappling-usgs** [comment]
Bummer. Those do look pretty convincingly Fahrenheitey. From the plots you've shown I'd be comfortable converting all but 745 to Celsius, especially if they all came from the same monitoring agency, but if the data are more complicated for other years/dates then yeah, I guess it's better to toss than to fit/assess models on bad data.

**Comment by limnoliver** [comment]
Thanks for the input, Alison. The good thing is the bad data from 745 seem to be from a single deployment (deployment = color), so I think that will be easy to isolate. The others are from the same agency/deployment.

**Comment by limnoliver** [comment]
Resolved [here](https://github.com/USGS-R/2wp-temp-observations/blob/master/5_data_munge/src/munge_data_files.R#L132-L134).
