### ISSUE TITLE
Missing WQP sites

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/2wp-temp-observations#22]
Recently, we had to make a change to how we are inventorying WQP data to use in our partitions. Instead of a national call to `whatWQPdata` (which used to work, but now throws a 504), we are looping through states and asking `whatWQPdata` in each state. Sometimes, we have to split the state in cases where the state has too much data (e.g., Florida). 

This solution works great for sites that have a state label. Some do not. In some instances, these sites are out of the country and should not be included in our dataset. In other instances, the sites are missing the state label in error, and should be included in our dataset. This amounts to thousands of sites, with > million records.

The real problem is that we don't know we are missing these sites, only that I know they're missing because I've archived old pulls and made comparisons. 

Possible solutions I have thought of:

- Looping by HUCs, though I strongly suspect there are many sites missing HUC labels as well.
- Looping through bounding boxes across the US. This would use the sites lat/long, and as far as I know, there aren't missing values in those columns.

**Comment by aappling-usgs** [comment]
I'll second the bounding boxes idea. I think I've seen missing HUC info in sites with missing state codes, too.

**Comment by aappling-usgs** [comment]
Also wondering if there's any possibility of getting WQP to fix the 504 issue
