### ISSUE TITLE
QAQC Issue (#26 ) Follow-up 

### ISSUE THREAD

**Issue by RAtshan** [USGS-R/2wp-temp-observations#30]
@limnoliver had a few question after viewing approach II (issue #26) results:

1.  The number of sites with 1 observation on given day. How many observation are in each group?
         We will find the number of observation and the number of flagged observation per group using the same approach that 
         we discussed during 9/25 meeting. 
2. How often are we using the fixed-value? How often are thresholds calculation too wide (large std-value) or too narrow (small 
    std-value)?
        We will find the number of groups that used the fixed value to calculated the threshold intervals. Then, we will find the 
        number of groups with a small and large std-values.
4.  Is approach 2 missing any outliers (false-negatives)? 
          We will create time-series plots for sites that have low number of observation (e.g. n <3) and sites with high std-values 
          (e.g. std > 15) without flagged observation:
         timeseries plots with day of the year on the x-axis, and daily temperature on the y-axis. Then, we will investigate any 
         suspicious values (e.g. a value that looks like  an outlier but wasn't flagged as outlier).

**Comment by limnoliver** [comment]
Thanks Rasha. A few follow-up points:

1) The proposed approach is grouping by site-day of year (DOY). I want to know what proportion of these groupings have 1, 2, 3 observations (and so on). Most will have very few observations, and I suspect you are reverting to the standard threshold width in those cases. How many site-days are "enough" to capture the normal variability for that site at that day of year?

**Comment by RAtshan** [comment]
A summary of what @limnoliver and I would like to further investigate in the QAQC (site-DOY  approach):

1. Make the necessary adjustment to scatter plot code. Divide by the correct parameter.
2. Select a site with a many recoded observation over time, Then, see how many observations are required to calculate mean and std for a group (site on doy).  
3. Experiment with site-doy groups that have 1 observation: 
          - Create day bins with approximately (+,-) 5 days and investigate what is the data availability, how many groups have 1 
            observation.
           - or combine a site with 1 observation on doy with other sites in the same latitude-bin that have 1 observation on the 
             same doy.
