### ISSUE TITLE
Multiple matched reaches

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/2wp-temp-observations#35]
I'm trying to create a concise crosswalk between sites and what reach they were matched to. In your plotting examples, you use the column `seg_id_reassigned` to plot the matched segments, so I assume this is the "matched" column. While doing this, I realized there are many duplicated site ids in the file `6_network/out/site_flowlines.rds.ind`, which I _think_ means a site was matched to multiple reaches. I think this has to do with the part of the algorithm that looks to see if the site is closer to the endpoint of the upstream reach, but I'm not sure how to resolve the data to a single matched reach per site id. 

```
library(scipiper)
library(dplyr)
library(ggplot2)
# id is a numeric ID that was created and is 1:nrow(sites)
matched <- readRDS(sc_retrieve(''6_network/out/site_flowlines.rds.ind", 'getters.yml')) %>%
     group_by(matched, id) %>%
     mutate(n = n())

# how many sites have more than one match?
length(unique(matched$id[matched$n > 1]))
# [1] 6935

# look at a site that was matched four times (site with the most matches)
top <- filter(matched, n == 4)

# plot the four reaches that were matched to this site, plus the original reach match
top <- filter(matched_dups, n == 4)
# original match
original <- filter(matched, seg_id_reassign %in% '31347') %>% distinct(Shape)

ggplot() +
  geom_sf(data =top$Shape, aes(color = factor(top$seg_id_reassign))) +
  geom_sf(data = top$Shape_site, color = 'red') +
  geom_sf(data = original$Shape, color = 'black')
```

![image](https://user-images.githubusercontent.com/15788176/103814021-a0b30c00-5026-11eb-8334-045a5f5ff239.png)

**Comment by wdwatkins** [comment]
I agree this is definitely happening with sites that are moved upstream.  Some of this is explained by sites with two upstream reaches (e.g. the one in the plot ☝️ — returning 31344 and 31345 is the expected behavior: https://github.com/USGS-R/2wp-temp-observations/blob/master/6_network/src/match_sites_reaches.R#L61).  That function would be the place to adjust that logic.

I am digging into why 33609 and 30271 are also here.  I suspect its a geofabric issue (i.e. 30271 and 33609 are also mapped as upstream of the black reach).  If so, and there wasn't a fix from the fabric side, we could probably compute another round of distance from the site to endpoint of the matched reaches, and only keep the top 2 (unless there are spots where 3 segments combine).

**Comment by wdwatkins** [comment]
Yep, its coming from the geofabric.  Here's the reach above, working with the raw geofabric:
```
gf_reaches <- sf::read_sf('6_network/in/GFv1.1.gdb', layer='nsegment_v1_1') %>%
    mutate_at(c("tosegment_v1_1"), .funs = na_if, 0) %>% # tosegment is the downstream segment to which water flows next. replace 0 (none next) with NA
    st_zm(drop = TRUE, what = "ZM") %>% #M dimension is inconsistent; prevents some subsetting
    rename(seg_id = nsegment_v1_1, to_seg = tosegment_v1_1,
           shape_length = Shape_Length)

filter(reach_endpoints, to_seg == 31347) #31347 is the reach above with 4 matches
# A tibble: 4 x 7
# Rowwise: 
  seg_id to_seg seg_id_nhm Version shape_length                                                                                Shape end_points     
   <int>  <int>      <int> <chr>          <dbl>                                                                <MULTILINESTRING [m]> <list>         
1  30271  31347      30271 1              6454.                                             ((-105736.5 2495964, -110589.1 2491709)) <POINT [m] [2]>
2  31344  31347      31344 1             17223. ((-159031.8 2489968, -159038.7 2490001, -159045.7 2490027, -159060.6 2490042, -15... <POINT [m] [2]>
3  31345  31347      31345 1             16502. ((-159529.2 2501827, -159420.3 2501810, -159400.1 2501801, -159393.1 2501773, -15... <POINT [m] [2]>
4  33609  31347      33609 1              3742. ((-100706.1 2477120, -100956.8 2477412, -102081.5 2476447, -102093.5 2476448, -10... <POINT [m] [2]>
```

I checked a handful of the sites with 3 matching reaches and they are the same.  I'll ask Blodgett about it.

**Comment by limnoliver** [comment]
What was the logic for when this happened? Or, did you not choose, and that's why it returned all matches? I think in these cases we should stick to the original match since the 2+ upstream reaches could be very different from one another, so choosing one seems dubious.

**Comment by wdwatkins** [comment]
Right, there isn't any further modification after the upstream reaches are found.  I think I discussed this with either you or Alison at some point last year.  But keeping the original match when there are multiple upstream should be an easy change, and I think should eliminate all the scenarios ☝️  that would depend on geofabric nuancess.  I'll make a PR

**Comment by limnoliver** [comment]
I've made a few changes to `6_network` so will PR right now.
