### ISSUE TITLE
Switch WQP inventory to year (rather than by state)

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/2wp-temp-observations#39]
Recently, we had to change our inventory of national WQP to iterate through states. We weren't totally satisfied with this approach (see Issue #22). Jim Kreft mentioned we can now query by year, so I'd like to try that approach.

I think this is a relatively small code change. The state iteration happens [here](https://github.com/USGS-R/2wp-temp-observations/blob/master/1_wqp_pull.yml#L43-L58), so would need to be replaced with a "year" iteration. The heart of the iteration through states happens [here](https://github.com/USGS-R/2wp-temp-observations/blob/master/1_wqp_pull/src/wqp_inventory.R#L86). 

I think the steps are:

- install the latest version of dataRetrieval
- figure out what the start year should be. This can be done by looking at data availability through time from the existing `5_data_munge/out/wqp_daily_nodepths.rds` file. But for experimentation, this could be a few recent years.
- Experiment with asking for all sites in the U.S. with temperature data by year (e.g., using `dataRetrieval::whatWQPdata`). How long does it take to query for sites by a year? Can we query by multiple years? Does this query return sites without state names, that is, does it solve the problem in #22?
- Compare a whatWQPdata call using a year (say 2018) to how long it takes to pull a single state - say Wisconsin. Is it faster or slower?
- If this seems promising, start changing the code to iterate through year versus through state. I think most of this happens [here](https://github.com/USGS-R/2wp-temp-observations/blob/master/1_wqp_pull/src/wqp_inventory.R).

**Comment by RAtshan** [comment]
Below are the findings from experimenting with `dataRetrieval::whatWQPdata`  to retrieve the US temperature data by year: 

To test the required time to retrieve the US temperature data by year, we retrieved all sites types of temperature data using one, two, and three years. 

-  **How long does it take to query for sites by a year?** 
It took 2.91 seconds to retrieve one year of temperature data for all sites type.
It took 58.25 seconds to retrieve two years of temperature data for all sites type.
It took 117.61 seconds to retrieve three years of temperature data for all sites type.

**R Code:**
```
all_vars <- c("Temperature", "Temperature, sample",
              "Temperature, water", "Temperature, water, deg F")
sites_type <- c("Lake, Reservoir, Impoundment", "Stream", "Wetland")

tic('test_2_years')
 sites_by_date <- whatWQPdata(siteType = sites_type,
                              sampleMedia = c('water', 'Water'),
                              characteristicName = all_vars,
                              startDateLo = "2017-01-01",
                              startDateHi = "2018-12-31")
 toc() 
sites_wo_state_names = sum(sites_by_date$StateName == '')
```

**R Results:**

Retrieving one year of temperature data: 
test_1_years: 2.91 sec elapsed
 sites_wo_state_names: 123

Retrieving two year of temperature data: 
test_2_years: 58.25 sec elapsed
 sites_wo_state_names: 192

Retrieving two year of temperature data: 
test_3_years:  117.61 sec elapsed
 sites_wo_state_names: 261


- **Can we query by multiple years?** 
Yes, we can query up to three years of temperature data in one code execution. 


- **Does this query return sites without state names, that is, does it solve the problem in #22?**
Yes, this query return sites without state names. Yes, this approach solves the problem in #22 
See R-code results above for the number of retrieved sites without State names. 


![image](https://user-images.githubusercontent.com/65974907/113719027-d3ff4880-96b2-11eb-93f7-3c92b7cdf3e6.png)


- **Compare a `whatWQPdata` call using a year (say 2018) to how long it takes to pull a single state - say Wisconsin. Is it faster or slower?**

To compare `whatWQPdata` call using the 2018 year and WI, we timed how long it takes to retrieve the temperature data for stream sites and for all sites types. 

**R Code:**
```
tic("all_wi_stream")
all_wi_stream <- whatWQPdata(siteType = 'Stream',
                         sampleMedia = c('water', 'Water'),
                         characteristicName = all_vars,
                         statecode = 'WI')
toc()
table(all_wi_sites$MonitoringLocationTypeName) # counts of the type of sites aviable. 
sites_wo_state_names = sum(all_wi_stream$StateName == '')

tic("all_2018_stream") # Function tic starts a stopwatch timer.
all2018_stream <- whatWQPdata(siteType = 'Stream', 
                       sampleMedia = c('water', 'Water'),
                       characteristicName = all_vars,
                       startDateLo = '2018-01-01', startDateHi = '2018-12-31')
toc() # Updates the elapsed time since the stopwatch timer was started.
# getting count of empty rows in the returned dataframe
sites_wo_state_names = sum(all2018_stream$StateName == '')
table(all2018_stream$MonitoringLocationTypeName)
```

**R Results:**

all_wi_stream: 29.95 seconds elapsed
vs 
all_2018_stream: 20.91 sec elapsed
sites_wo_state_names = 24
 
From the above results we notice that it takes less time to retrieve the nation's stream temperature data using *year* approach in comparison to  the time it take to retrieve Wisconsin's stream data using the *state* approach. Also, we are able to retrieve sites that don't have state names . 

**R Code:**
```
tic("all_wi_sites")
all_wi_sites <- whatWQPdata(siteType = sites_type, #'Stream'
                         sampleMedia = c('water', 'Water'),
                         characteristicName = all_vars,
                         statecode = 'WI')
toc()
table(all_wi_sites$MonitoringLocationTypeName) # counts of the type of sites aviable. 
sites_wo_state_names = sum(all_wi_stream$StateName == '')

tic("all_2018_sites") # Function tic starts a stopwatch timer.
all2018_sites <- whatWQPdata(siteType = sites_type, 
                       sampleMedia = c('water', 'Water'),
                       characteristicName = all_vars,
                       startDateLo = '2018-01-01', startDateHi = '2018-12-31')
toc() # Updates the elapsed time since the stopwatch timer was started.
# getting count of empty rows in the returned dataframe
sites_wo_state_names = sum(all2018_sites$StateName == '')
```

**R Results:**

all_wi_sites: 24.38 sec elapsed
vs
all_2018_sites: 1.82 sec elapsed
sites_wo_state_names = 123

Similarly, the results shows that it takes less time to retrieve the nation's all sites types temperature data using the *year* approach in comparison to  the time it take to retrieve Wisconsin's all sites types temperature data using the *state* approach.

**Comment by jread-usgs** [comment]
Interesting 🤔 

for this: 
> How long does it take to query for sites by a year?
It took 2.91 seconds to retrieve one year of temperature data for all sites type.
It took 58.25 seconds to retrieve two years of temperature data for all sites type.
It took 117.61 seconds to retrieve three years of temperature data for all sites type.

is this result impacted by the years that were queried, or is there a scaling issue with requesting multiple years that creates a non-linear query time? I.e., is it faster (as it looks like it is) to loop through the three years individually and bind the result together vs query all three years at once?

**Comment by limnoliver** [comment]
Good questions, Jordan. (and Rasha updated text, but note we're just querying sites, not actually pulling data yet).

Also, Rasha, a warning about WQP. I've noticed in the past that WQP does some sort of caching, such that the first call to WQP will be slow, but if you make the same call again, it will be much faster.

**Comment by RAtshan** [comment]
Yes, I noticed that making the same call again, runs much faster. For example, the first call to retrieve one year of temperature data inventory for all sites type on my machine 60.56 seconds.

**Comment by limnoliver** [comment]
And how long does it take to pull all three?

**Comment by RAtshan** [comment]
It took 117.61 seconds to pull the inventory for the three years (2016, 2017, and 2018) in one run.

test_3_years: 117.61 sec elapsed

**Comment by RAtshan** [comment]
**- Start changing the code to iterate through year versus through state:**

Here's the PR to pull the WQP data inventory by year #40.

**Comment by RAtshan** [comment]
**Years Approach vs the Bounding Box Approach** 

Now, I am comparing between pulling the WQP data inventory using the years approach vs the bounding box approach. To find the superior approach to pull WQP data inventory, I selected a spatial area about the size of two states and compared the required time to pull the WQP data inventory using two trials. First, I tracked the required time to pull the WQP data inventory for the entire bounding box while partitioning the years (year’s approach): (1890 - 1979), (1980 - 1989), (1990 – 1999), (2000 - 2009), (2010 - 2015), and (2016 – 2021). Then, I tracked the required time to pull WQP data inventory by dividing the bounding box into smaller bounding boxes (bounding box approach). I repeated this process for four different spatial areas: (-111, 37, -102, 45), (-93.43, 36, -89, 38.1), (-109, 31, -102, 41), and (-88, 37, -80, 41). 

From the timed trials, I found that pulling WQP using the bounding box approach is superior to the year’s approach. For example, pulling the WQP data inventory for the bounding box (-111, 37, -102, 45) using the bounding box approach required 44.61 seconds. While pulling the WQP using the year’s approach required 69.22 seconds. The required time to pull the WQP data inventory varies based on the volume of sites and data available at the bounding box. We can group bounding boxes that have fewer data and site volume and split the bounding boxes that have high data and site volume into smaller bounding boxes.  For example, I was able to pull (-88, 37, -80, 41) WQP inventory data by splitting the bounding box into four smaller bounding boxes. In the meantime, I had to split the other three spatial areas into six smaller bounding boxes to pull the WQP inventory data. Both approaches (years and bounding box) returned the 65 variables and the same number of sites. Also, both approaches returned sites that don't have state names.

See R code and results below from the trials that I performed using `Stream`.  I also experimented using all site types, springs, and lakes/reservoirs. 


**R Code:**
```
library(tidyverse)
library(dataRetrieval)
library(tictoc)

all_vars <- c("Temperature", "Temperature, sample",
              "Temperature, water", "Temperature, water, deg F")
sites_type <- c("Lake, Reservoir, Impoundment", "Stream", "Wetland")


# Setting longitude and latitude coordinates for 2 states (Wyoming, Colorado).
# bBox = c(West, South, East, North)
long_lat_coord <- c(-111, 37, -102, 45) 
# # Partition states longitude and latitude coordinates.
long_lat_coord_A <- c(-105.1, 37, -102, 41.1)
long_lat_coord_B <- c(-108.1, 37, -104.9, 41.1)
long_lat_coord_C <- c(-111, 37, -107.9, 41.1)
long_lat_coord_D <- c(-105.1, 40.9, -102, 45)
long_lat_coord_E <- c(-108.1, 40.9, -104.9, 45)
long_lat_coord_F <- c(-111, 40.9, -107.9, 45)

# Setting longitude and latitude coordinates for 2 states (Kansas and Missouri).
long_lat_coord <- c(-102, 36, -89, 40)
# Partition states longitude and latitude coordinates.
long_lat_coord_A <- c(-93.43, 36, -89, 38.1) 
long_lat_coord_B <- c(-97.76, 36, -93.23, 38.1)
long_lat_coord_C <- c(-102, 36, -97.56, 38.1)
long_lat_coord_D <- c(-93.43, 37.9, -89, 40)
long_lat_coord_E <- c(-97.76, 37.9, -93.23, 40)
long_lat_coord_F <- c(-102, 37.9, -97.56, 40)
# Setting longitude and latitude coordinates for 2 states (Colorado and New Mexico).
long_lat_coord <- c(-109, 31, -102, 41) 
# # Partition states longitude and latitude coordinates.
long_lat_coord_A <- c(-105.6, 31, -102, 34.43)
long_lat_coord_B <- c(-105.6, 34.23, -102, 37.76)
long_lat_coord_C <- c(-105.6, 37.56, -102, 41)
long_lat_coord_D <- c(-109, 31, -105.4, 34.43)
long_lat_coord_E <- c(-109, 34.23, -105.4, 37.76)
long_lat_coord_F <- c(-109, 37.56, -105.4, 41)

# Pulling WQP data inventory for entire bounding box.
tic("coord")
bbox_sites <- whatWQPdata(siteType = "Stream",
                          sampleMedia = c('water', 'Water'),
                          characteristicName = all_vars,
                          bBox = long_lat_coord)
toc()
sites_wo_state_names = sum(bbox_sites$StateName == '')
unique_site_time_data <- length(unique(bbox_sites$MonitoringLocationIdentifier))
# Pulling WQP data inventory for entire bounding box using six time partitions.
# splitting the time on 6 chunks.
tic("coord_time_partitions")
# first time chunk (1890 - 1989)
bbox_sites_timeA <- whatWQPdata(siteType = "Stream",
                                sampleMedia = c('water', 'Water'),
                                characteristicName = all_vars,
                                bBox = long_lat_coord,
                                startDateLo = '1890-01-01', startDateHi = '1979-12-31')


# Second time chunk (1980 - 1989)
bbox_sites_timeB <- whatWQPdata(siteType = "Stream",
                                sampleMedia = c('water', 'Water'),
                                characteristicName = all_vars,
                                bBox = long_lat_coord,
                                startDateLo = '1980-01-01', startDateHi = '1989-12-31')
# third time chunk (1990- 1999)
bbox_sites_timeC <- whatWQPdata(siteType = "Stream",
                                sampleMedia = c('water', 'Water'),
                                characteristicName = all_vars,
                                bBox = long_lat_coord,
                                startDateLo = '1990-01-01', startDateHi = '1999-12-31')
# fourth time chunk (2000 - 2009)
bbox_sites_timeD <- whatWQPdata(siteType = "Stream",
                                sampleMedia = c('water', 'Water'),
                                characteristicName = all_vars,
                                bBox = long_lat_coord,
                                startDateLo = '2000-01-01', startDateHi = '2009-12-31')
# fifth time chunk (2010 - 2015)
bbox_sites_timeE <- whatWQPdata(siteType = "Stream",
                                sampleMedia = c('water', 'Water'),
                                characteristicName = all_vars,
                                bBox = long_lat_coord,
                                startDateLo = '2010-01-01', startDateHi = '2015-12-31')
# sixth time chunk (2016 - 2021)
bbox_sites_timeF <- whatWQPdata(siteType = "Stream",
                                sampleMedia = c('water', 'Water'),
                                characteristicName = all_vars,
                                bBox = long_lat_coord,
                                startDateLo = '2016-01-01', startDateHi = '2021-04-16')

# Combining the WQP data pulled using six time partitions to create a dataframe.
all_dat_time_partitions <- bind_rows(bbox_sites_timeA, bbox_sites_timeB,
                                     bbox_sites_timeC, bbox_sites_timeD,
                                     bbox_sites_timeE, bbox_sites_timeF) %>%
  group_by(MonitoringLocationIdentifier) %>%
  summarize(resultCount = sum(resultCount)) %>%
  distinct()
unique_site_time_data <- length(unique(all_dat_time_partitions$MonitoringLocationIdentifier))
toc()

# Pulling WQP data inventory for bounding box by splitting it to six bounding boxes.
tic("coord_partitions")
# Pulling WQP data inventory for bounding box 1
bbox_sites_coordA <- whatWQPdata(siteType = "Stream",
                                 sampleMedia = c('water', 'Water'),
                                 characteristicName = all_vars,
                                 bBox = long_lat_coord_A)
# Pulling WQP data inventory for bounding box 2.
bbox_sites_coordB <- whatWQPdata(siteType = "Stream",
                                 sampleMedia = c('water', 'Water'),
                                 characteristicName = all_vars,
                                 bBox = long_lat_coord_B)
# Pulling WQP data inventory for bounding box 3.
bbox_sites_coordC <- whatWQPdata(siteType = "Stream",
                                 sampleMedia = c('water', 'Water'),
                                 characteristicName = all_vars,
                                 bBox = long_lat_coord_C)
# Pulling WQP data inventory for bounding box 4.
bbox_sites_coordD <- whatWQPdata(siteType = "Stream",
                                 sampleMedia = c('water', 'Water'),
                                 characteristicName = all_vars,
                                 bBox = long_lat_coord_D)
# Pulling WQP data inventory for bounding box 5.
bbox_sites_coordE <- whatWQPdata(siteType = "Stream",
                                 sampleMedia = c('water', 'Water'),
                                 characteristicName = all_vars,
                                 bBox = long_lat_coord_E)
# Pulling WQP data inventory for bounding box 6.
bbox_sites_coordF <- whatWQPdata(siteType = "Stream",
                                 sampleMedia = c('water', 'Water'),
                                 characteristicName = all_vars,
                                 bBox = long_lat_coord_F)

all_dat_bbox_partitions <- bind_rows(bbox_sites_coordA, bbox_sites_coordB,
                                     bbox_sites_coordC, bbox_sites_coordD,
                                     bbox_sites_coordE, bbox_sites_coordF) %>%
  group_by(MonitoringLocationIdentifier) %>%
  summarize(resultCount = max(resultCount)) %>%
  distinct()
toc()
length(unique(all_dat_bbox_partitions$MonitoringLocationIdentifier))
# Getting CO/NM 2 sites that have missing statenames.


#Setting longitude and latitude coordinates for 2 states (Ohio and Indiana).
# bBox = c(West, South, East, North)
long_lat_coord <- c(-88, 37, -80, 41)
# # Partition states longitude and latitude coordinates.
long_lat_coord_A <- c(-84.1, 37, -80, 39.1)
long_lat_coord_B <- c(-84.1, 38.9, -80, 41)
long_lat_coord_C <- c(-88, 37, -83.9, 39.1)
long_lat_coord_D <- c(-88, 38.9, -83.9, 41)
tic("coord")
bbox_sites <- whatWQPdata(siteType = "Stream",
                          sampleMedia = c('water', 'Water'),
                          characteristicName = all_vars,
                          bBox = long_lat_coord)
toc()
# unique_sites <- length(unique(bbox_sites$MonitoringLocationIdentifier))

# Pulling WQP data inventory for entire bounding box using four time partitions.
# splitting the time on 4 chunks.
tic("coord_time_partitions")
# first time chunk (1890 - 1989)
bbox_sites_timeA <- whatWQPdata(siteType = "Stream",
                                sampleMedia = c('water', 'Water'),
                                characteristicName = all_vars,
                                bBox = long_lat_coord,
                                startDateLo = '1890-01-01', startDateHi = '1989-12-31')

#  Second time chunk (1990 - 1999)
bbox_sites_timeB <- whatWQPdata(siteType = "Stream",
                                sampleMedia = c('water', 'Water'),
                                characteristicName = all_vars,
                                bBox = long_lat_coord,
                                startDateLo = '1990-01-01', startDateHi = '1999-12-31')
# third time chunk (2000- 2009)
bbox_sites_timeC <- whatWQPdata(siteType = "Stream",
                                sampleMedia = c('water', 'Water'),
                                characteristicName = all_vars,
                                bBox = long_lat_coord,
                                startDateLo = '2000-01-01', startDateHi = '2009-12-31')

# fourth time chunk (2010 - 2021)
bbox_sites_timeD <- whatWQPdata(siteType = "Stream",
                                sampleMedia = c('water', 'Water'),
                                characteristicName = all_vars,
                                bBox = long_lat_coord,
                                startDateLo = '2010-01-01', startDateHi = '2021-04-19')

# Combining the WQP data pulled using four time partitions to create a dataframe.
all_dat_time_partitions <- bind_rows(bbox_sites_timeA, bbox_sites_timeB,
                                     bbox_sites_timeC, bbox_sites_timeD) %>%
  group_by(MonitoringLocationIdentifier) %>%
  summarize(resultCount = sum(resultCount)) %>%
  distinct()
unique_site_time_data <- length(unique(all_dat_time_partitions$MonitoringLocationIdentifier))
toc()
##
tic("coord_partition1")
bbox_sites_coordA <- whatWQPdata(siteType = "Stream",
                                 sampleMedia = c('water', 'Water'),
                                 characteristicName = all_vars,
                                 bBox = long_lat_coord_A)

bbox_sites_coordB <- whatWQPdata(siteType = "Stream",
                                 sampleMedia = c('water', 'Water'),
                                 characteristicName = all_vars,
                                 bBox = long_lat_coord_B)

bbox_sites_coordC <- whatWQPdata(siteType = "Stream",
                                 sampleMedia = c('water', 'Water'),
                                 characteristicName = all_vars,
                                 bBox = long_lat_coord_C)

bbox_sites_coordD <- whatWQPdata(siteType = "Stream",
                                 sampleMedia = c('water', 'Water'),
                                 characteristicName = all_vars,
                                 bBox = long_lat_coord_D)
all_dat_bbox_partitions <- bind_rows(bbox_sites_coordA, bbox_sites_coordB,
                                     bbox_sites_coordC, bbox_sites_coordD) %>%
  group_by(MonitoringLocationIdentifier) %>%
  summarize(resultCount = sum(resultCount)) %>%
  distinct()
toc()
```

**R Results:**

- Coordinates (-111, 37, -102, 45)
Years approach:
`> coord_time_partitions: 69.22 sec elapsed`
Bounding box approach:
`> coord_partitions: 44.61 sec elapsed`
The number of sites retrieved: 19464 

- Coordinates are (-102, 36, -89, 40)
Years approach:
`> coord_time_partitions: 50.61 sec elapsed`
Bounding box approach:
`> coord_partitions: 46.42 sec elapsed`
The number of sites retrieved: 8682

- Coordinates are (-109, 31, -102, 41)
Years approach:
`> coord_time_partitions: 56.59 sec elapsed`
Bounding box approach:
`> coord_partitions: 42.2 sec elapsed`
The number of sites retrieved: 14102

- Coordinates are (-88, 37, -80, 41)
Years approach:
`> coord_time_partitions: 45.23 sec elapsed`
Bounding box approach:
`> coord_partitions: 27.92 sec elapsed`
The number of sites retrieved: 21723

**Comment by limnoliver** [comment]
Thanks Rasha. Good to know we can get the same data with time or space chunks, and that the `bbox` approach is generally faster. I suspect this is in part because each site is returned multiple times in the time approach. 

For other pros and cons: generally, we're still sort of guessing about how many sites are in each time or space chunk, and therefore how many chunks we have to pull. My guess is that time is relatively consistent in that most of the country follows the same general pattern of number of sites through time. Beyond that, I think the benefit of the year vs bbox approach might be project specific. Time certainly makes sense if you want to regularly "add on" to a pull - e.g., update data once a year. It's also nice to be able to do an analysis of `n records` through time without having to pull the actual data.

**Comment by jread-usgs** [comment]
> Time certainly makes sense if you want to regularly "add on" to a pull - e.g., update data once a year. It's also nice to be able to do an analysis of n records through time without having to pull the actual data.

This seems to be perhaps the most compelling reason of all - we do that particular thing a lot. But also based on my experience there is a lot of corrections of records that happens through time, so small changes can happen to 2005 data in 2021 for example.

**Comment by limnoliver** [comment]
Yes, I think one solution is that you could always do the inventory through all of the time chunks (that step is relatively quick) and compare the number of records between the old and new inventories. Then pull only sites that have n record changes. Wouldn't catch actual result modifications, but would catch `n record` changes.
