### ISSUE TITLE
Typo in `cfg` file

### ISSUE THREAD

**Issue by padilla410** [USGS-R/2wp-temp-observations#49]
I am reviewing the workflow of this repo for another project and I noticed that there seems to be a bug in [`wqp_partition_config.yml`](https://github.com/USGS-R/2wp-temp-observations/blob/174875b69c335436bf5acdeee8a53e5334ac72de/1_wqp_pull/cfg/wqp_partition_config.yml#L6-L7): the note says the max WQP pull size is 25,000 but the code says 250,000. 

Not sure if this is a typo, but seemed drawing attention to it if it is.

**Comment by limnoliver** [comment]
Thanks Julie - the code is correct. I think the text was burrowed from other code bases that used this pattern, and we experimented/iterated here and found 250k to work for us. So I think the text and code are just outdated relative to each other.

**Comment by padilla410** [comment]
Thanks for the double check, Sam. I'll close this.
