### ISSUE TITLE
Incorporate hydrologic addressing into pipeline

### ISSUE THREAD

**Issue by mhines-usgs** [USGS-R/2wp-temp-observations#7]
input of stationId, lat, long required
output would then include a reachId

**Comment by jread-usgs** [comment]
My view on this task (shared by Sam too?) is that there is a quick and dirty addressing that will help us with initial visualization. We have used "nearest neighbor" algorithms to do this in the past. As we move into the later stages of the project (beyond the initial visualization of data inventory), we'll need to work up a more rigorous addressing routine, and likely ask for some consult from the GeoIntel branch to do so. I can clarify or discuss this if there are questions.

**Comment by mhines-usgs** [comment]
👍 @limnoliver where are the data you mentioned that are already pulled stored?

**Comment by limnoliver** [comment]
WQP (and eventually NWIS) located here: https://drive.google.com/drive/u/0/folders/1P58Y7vmAkTMQufwD4EeJDiZLyjAzKSPD. I'll give you access!

**Comment by limnoliver** [comment]
Also @mhines-usgs - the "inventory" files for both WQP and NWIS in the inout folder have all the unique sites (and I think lat long) so that you can see the unique locations without having to mess with the data themselves.

**Comment by mhines-usgs** [comment]
Awesome, thanks for that tip :) I just downloaded everything but will check the inout documents

**Comment by mhines-usgs** [comment]
I made a PR with an attempt to use Jordan's suggestion of searchTree and knnLookup, as well as another which apparently also uses similar underlying functions, because they return similar data. I haven't figured out how to properly retrieve the reachID with the response yet though. https://github.com/USGS-R/2wp-temp-observations/pull/8/files

**Comment by mhines-usgs** [comment]
Took another approach altogether, but still would like to try and speed it up if possible. Even after geospatially subsetting the points data to eliminate points outside the reach/network layer's boundary https://github.com/USGS-R/2wp-temp-observations/pull/8/files#diff-f163fbc2738a274b80b6c132f307f56b

**Comment by limnoliver** [comment]
Do you know which part is taking a long time? At first glance, I thought the loops might be slowing it down if you have many sites -- do you think that's the case?

**Comment by jread-usgs** [comment]
I have some other old code that I dug up that was doing similar addressing (site point to reach). Looks like this:

```r
subset_closest <- function(features, sp.list){
  
  features <- features[features$order_ > 1, ]
  box.cent <- matrix(rep(NA, length(features) *2), ncol = 2)
  
  ptm <- proc.time()
  for (j in 1:nrow(box.cent)){
    box.cent[j, ] <- features[j, ]@lines[[1]]@Lines[[1]]@coords[1, 1:2]
  }
  print(proc.time() - ptm)
  
  
  reach.pts <- SpatialPoints(coords = box.cent, proj4string = CRS(proj4string(features)))
  tree <- createTree(coordinates(reach.pts))
  inds <- c()
  for (sp in sp.list){
    inds <- c(inds, knnLookup(tree, newdat=coordinates(sp), k=1))
  }
  inds <- unique(inds) %>% as.vector()
  
  return(features[inds, ])
}
```

and I used it like this:
```r
noreast_reaches <- subset_closest(nwm_rivers, noreast_sites)
```

Is that helpful? I used it to create maps that just plotted the reaches that were estimated to be monitored by the site points:
![basemap_nhd_grey](https://user-images.githubusercontent.com/2349007/59852430-6abf1180-9334-11e9-906d-e3c0261eeef9.png)
![NorEaST_features](https://user-images.githubusercontent.com/2349007/59852432-6abf1180-9334-11e9-8a8d-6b81ec76e6d3.png)

**Comment by mhines-usgs** [comment]
The slow part is the dist2Line part it seems, I could try to parallelize it or just use what Jordan shared here to see if it's any faster.
